version: "3.8"

services:
  gradle-app:
    image: sunggyu496/spring-pet-clinic:latest   # Gradle로 빌드한 이미지의 이름
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"         # 각 replica의 CPU 사용 한도
          memory: "512M"       # 각 replica의 메모리 사용 한도
        reservations:
          cpus: "0.25"        # 예약 CPU
          memory: "256M"       # 예약 메모리
      restart_policy:
        condition: on-failure   # 실패 시 재시작 정책
    ports:
      - "8080:8080"              # 외부 포트 8080을 서비스 컨테이너의 8080 포트에 연결
    environment:
      - SPRING_PROFILES_ACTIVE=prod   # Spring 환경 프로파일 (필요한 경우)

networks:
  default:
    driver: overlay  # 여러 노드에서 네트워크 연결을 가능하게 하는 Swarm 네트워크
