name: Access SSH TEST

on:
  workflow_dispatch:  # 수동으로 트리거할 수 있도록 설정

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH to Remote Server and Deploy Stack
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Docker Swarm Stack Deploy
          echo "Hello, World!"
